name: deploy

on:
  push:
    branches:
      - feature/pipelines

jobs:
  deploy-srs:
    name: deploy-acceptance
    runs-on: ubuntu-18.04
    env:
      ENV_DIR: '$HOME'
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - uses: actions/checkout@v2
      - name: Prepare config file
        uses: falnyr/replace-env-vars-action@master
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        with:
          filename: config.ci.py
      - run: mv config.ci.py config.py
      - name: Setup SSH key
        run: |
          mkdir -p /root/.ssh
          ssh-keyscan -H "${SSH_HOST}" >> /root/.ssh/known_hosts
          eval `ssh-agent -s`
          echo "${DEPLOY_SSH_KEY}" | tr -d '\r' | ssh-add -